import { useState } from "react";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Loader2, FileText, CheckCircle, AlertCircle, Download, Brain, Sparkles } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import DragDropUpload from "@/components/drag-drop-upload";

interface DocumentGap {
  missingDocuments: string[];
  canAutoGenerate: string[];
  requiresExternalUpload: string[];
  generationPriority: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
}

interface GeneratedDocument {
  filename: string;
  content: string;
  documentType: string;
  metadata: any;
  autoGenerated: boolean;
}

interface AuditResult {
  complianceAnalyses: any[];
  documentGaps: DocumentGap;
  generatedDocuments: GeneratedDocument[];
  uploadRequests: string[];
  summary: {
    total: number;
    compliant: number;
    nonCompliant: number;
    partial: number;
    insufficientData: number;
    criticalIssues: number;
    highRiskIssues: number;
    documentsGenerated: number;
    documentsNeeded: number;
    aiPowered?: boolean;
  };
}

export default function DocumentGeneration() {
  const [auditResult, setAuditResult] = useState<AuditResult | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [uploadedFiles, setUploadedFiles] = useState<File[]>([]);
  const { toast } = useToast();
  const queryClient = useQueryClient();

  const auditWithGenerationMutation = useMutation({
    mutationFn: async (organizationId: string) => {
      const response = await fetch('/api/audit/analyze-with-generation', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ organizationId })
      });
      
      if (!response.ok) {
        throw new Error('Failed to perform audit with document generation');
      }
      
      return response.json();
    },
    onSuccess: (data) => {
      setAuditResult(data);
      const aiPowered = data.summary.aiPowered ? " using AI" : "";
      toast({
        title: "Smart Audit Complete",
        description: `Generated ${data.summary.documentsGenerated} documents${aiPowered}, identified ${data.summary.documentsNeeded} additional needs`,
      });
      queryClient.invalidateQueries({ queryKey: ['/api/documents'] });
    },
    onError: (error) => {
      toast({
        title: "Audit Failed",
        description: error instanceof Error ? error.message : "Unknown error occurred",
        variant: "destructive",
      });
    },
  });

  const handleStartAuditWithGeneration = () => {
    setIsGenerating(true);
    auditWithGenerationMutation.mutate('default-org');
  };

  const getPriorityColor = (priority: string) => {
    switch (priority) {
      case 'CRITICAL': return 'bg-red-500';
      case 'HIGH': return 'bg-orange-500';
      case 'MEDIUM': return 'bg-yellow-500';
      case 'LOW': return 'bg-green-500';
      default: return 'bg-gray-500';
    }
  };

  const downloadDocument = (doc: GeneratedDocument) => {
    const blob = new Blob([doc.content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = doc.filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="container mx-auto py-6">
      <div className="flex items-center justify-between mb-6">
        <div>
          <h1 className="text-3xl font-bold">AI Document Generation</h1>
          <p className="text-gray-600 dark:text-gray-300">
            Automatically generate missing compliance documents and fill documentation gaps
          </p>
        </div>
        
        <Button 
          onClick={handleStartAuditWithGeneration}
          disabled={auditWithGenerationMutation.isPending || isGenerating}
          size="lg"
          className="bg-gradient-to-r from-blue-600 to-purple-600 hover:from-blue-700 hover:to-purple-700"
        >
          {auditWithGenerationMutation.isPending ? (
            <>
              <Loader2 className="mr-2 h-4 w-4 animate-spin" />
              AI Processing...
            </>
          ) : (
            <>
              <Brain className="mr-2 h-4 w-4" />
              Start AI-Powered Audit
              <Sparkles className="ml-2 h-4 w-4" />
            </>
          )}
        </Button>
      </div>

      {/* File Upload Section */}
      <Card className="mb-6">
        <CardHeader>
          <CardTitle className="flex items-center">
            <FileText className="mr-2 h-4 w-4" />
            Upload Existing Documents (Optional)
          </CardTitle>
          <CardDescription>
            Upload your current compliance documents for AI analysis and personalized document generation
          </CardDescription>
        </CardHeader>
        <CardContent>
          <DragDropUpload 
            onFilesUploaded={(files) => {
              setUploadedFiles(files);
              toast({
                title: "Files Ready",
                description: `${files.length} files uploaded and ready for analysis`,
              });
            }}
            maxFiles={10}
          />
        </CardContent>
      </Card>

      {auditWithGenerationMutation.isPending && (
        <Card className="mb-6">
          <CardHeader>
            <CardTitle className="flex items-center">
              <Loader2 className="mr-2 h-4 w-4 animate-spin" />
              AI-Powered Compliance Analysis
            </CardTitle>
            <CardDescription>
              Advanced AI is analyzing your documents and generating personalized compliance materials...
            </CardDescription>
          </CardHeader>
          <CardContent>
            <Progress value={66} className="w-full" />
            <p className="text-sm text-gray-600 dark:text-gray-300 mt-2">
              Phase 1: Document analysis • Phase 2: AI gap identification • Phase 3: Intelligent document generation
            </p>
          </CardContent>
        </Card>
      )}

      {auditResult && (
        <div className="space-y-6">
          {/* Summary Statistics */}
          <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
            <Card>
              <CardHeader className="pb-2">
                <CardTitle className="text-lg">Compliance Status</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="text-2xl font-bold text-green-600">
                  {auditResult.summary.compliant}
                </div>
                <p className="text-sm text-gray-600">of {auditResult.summary.total} requirements</p>
                <Progress 
                  value={(auditResult.summary.compliant / auditResult.summary.total) * 100} 
                  className="mt-2"
                />
              </CardContent>
            </Card>

            <Card>
              <CardHeader className="pb-2">
                <CardTitle className="text-lg flex items-center">
                  Generated Documents
                  {auditResult.summary.aiPowered && (
                    <Badge className="ml-2 bg-purple-100 text-purple-800">
                      AI-Powered
                    </Badge>
                  )}
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="text-2xl font-bold text-blue-600">
                  {auditResult.summary.documentsGenerated}
                </div>
                <p className="text-sm text-gray-600">
                  {auditResult.summary.aiPowered ? 'intelligently created' : 'automatically created'}
                </p>
                <CheckCircle className="h-6 w-6 text-green-500 mt-2" />
              </CardContent>
            </Card>

            <Card>
              <CardHeader className="pb-2">
                <CardTitle className="text-lg">Upload Requests</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="text-2xl font-bold text-orange-600">
                  {auditResult.summary.documentsNeeded}
                </div>
                <p className="text-sm text-gray-600">require manual upload</p>
                <AlertCircle className="h-6 w-6 text-orange-500 mt-2" />
              </CardContent>
            </Card>

            <Card>
              <CardHeader className="pb-2">
                <CardTitle className="text-lg">Critical Issues</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="text-2xl font-bold text-red-600">
                  {auditResult.summary.criticalIssues}
                </div>
                <p className="text-sm text-gray-600">immediate attention needed</p>
                <AlertCircle className="h-6 w-6 text-red-500 mt-2" />
              </CardContent>
            </Card>
          </div>

          {/* Document Gap Analysis */}
          {auditResult.documentGaps && (
            <Card>
              <CardHeader>
                <CardTitle>Document Gap Analysis</CardTitle>
                <CardDescription>
                  Analysis of missing documentation and generation status
                </CardDescription>
              </CardHeader>
              <CardContent>
                <div className="mb-4">
                  <Badge className={`${getPriorityColor(auditResult.documentGaps.generationPriority)} text-white`}>
                    {auditResult.documentGaps.generationPriority} Priority
                  </Badge>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  {auditResult.documentGaps.canAutoGenerate.length > 0 && (
                    <div>
                      <h4 className="font-semibold text-green-600 mb-2">✅ Auto-Generated</h4>
                      <ul className="text-sm space-y-1">
                        {auditResult.documentGaps.canAutoGenerate.map((doc, idx) => (
                          <li key={idx} className="text-gray-600 dark:text-gray-300">
                            • {doc.replace(/_/g, ' ').toLowerCase()}
                          </li>
                        ))}
                      </ul>
                    </div>
                  )}

                  {auditResult.documentGaps.requiresExternalUpload.length > 0 && (
                    <div>
                      <h4 className="font-semibold text-orange-600 mb-2">📤 Upload Required</h4>
                      <ul className="text-sm space-y-1">
                        {auditResult.documentGaps.requiresExternalUpload.map((doc, idx) => (
                          <li key={idx} className="text-gray-600 dark:text-gray-300">
                            • {doc.replace(/_/g, ' ').toLowerCase()}
                          </li>
                        ))}
                      </ul>
                    </div>
                  )}
                </div>
              </CardContent>
            </Card>
          )}

          {/* Generated Documents */}
          {auditResult.generatedDocuments.length > 0 && (
            <Card>
              <CardHeader>
                <CardTitle>Generated Documents</CardTitle>
                <CardDescription>
                  AI-generated compliance documents ready for use
                </CardDescription>
              </CardHeader>
              <CardContent>
                <div className="space-y-4">
                  {auditResult.generatedDocuments.map((doc, idx) => (
                    <div key={idx} className="flex items-center justify-between p-4 border rounded-lg">
                      <div className="flex-1">
                        <div className="font-medium flex items-center">
                          {doc.filename}
                          {doc.metadata?.aiGenerated && (
                            <Badge className="ml-2 bg-purple-100 text-purple-800 text-xs">
                              AI
                            </Badge>
                          )}
                        </div>
                        <div className="text-sm text-gray-600 dark:text-gray-300">
                          Type: {doc.documentType.replace(/_/g, ' ')} • 
                          {doc.metadata?.aiGenerated ? ' AI-generated' : ' Auto-generated'}
                        </div>
                        {doc.metadata?.regulatoryBasis && (
                          <div className="text-xs text-gray-500 mt-1">
                            Regulatory Basis: {doc.metadata.regulatoryBasis}
                          </div>
                        )}
                      </div>
                      <Button 
                        variant="outline" 
                        size="sm"
                        onClick={() => downloadDocument(doc)}
                      >
                        <Download className="h-4 w-4 mr-2" />
                        Download
                      </Button>
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>
          )}

          {/* Upload Requests */}
          {auditResult.uploadRequests.length > 0 && (
            <Alert>
              <AlertCircle className="h-4 w-4" />
              <AlertDescription>
                <strong>Action Required:</strong> The following documents need to be manually uploaded:
                <ul className="mt-2 ml-4 list-disc">
                  {auditResult.uploadRequests.map((req, idx) => (
                    <li key={idx}>{req}</li>
                  ))}
                </ul>
              </AlertDescription>
            </Alert>
          )}
        </div>
      )}
    </div>
  );
}