import OpenAI from 'openai';

// the newest OpenAI model is "gpt-4o" which was released May 13, 2024. do not change this unless explicitly requested by the user
const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });

export interface DocumentGenerationRequest {
  documentType: string;
  organizationName?: string;
  existingDocuments?: any[];
  specificRequirements?: string[];
  complianceGaps?: string[];
}

export interface GeneratedDocument {
  filename: string;
  content: string;
  documentType: string;
  metadata: {
    organization?: string;
    regulatoryBasis: string;
    generatedAt: string;
    confidenceScore?: number;
    aiGenerated: boolean;
  };
  autoGenerated: boolean;
}

export class AIDocumentGenerator {
  async generateComplianceDocument(request: DocumentGenerationRequest): Promise<GeneratedDocument> {
    const prompt = this.buildDocumentPrompt(request);
    
    try {
      const response = await openai.chat.completions.create({
        model: "gpt-4o",
        messages: [
          {
            role: "system",
            content: "You are an expert FAR Part 142 compliance document generator. Create professional, regulation-compliant documents that training centers can use immediately. Include all required fields, proper formatting, and regulatory references."
          },
          {
            role: "user",
            content: prompt
          }
        ],
        temperature: 0.3, // Low temperature for consistency
        max_tokens: 3000
      });

      const generatedContent = response.choices[0].message.content || '';
      
      return {
        filename: this.generateFilename(request.documentType),
        content: generatedContent,
        documentType: request.documentType,
        metadata: {
          organization: request.organizationName || 'Training Center',
          regulatoryBasis: this.getRegulatoryBasis(request.documentType),
          generatedAt: new Date().toISOString(),
          confidenceScore: 0.95, // High confidence for AI-generated content
          aiGenerated: true
        },
        autoGenerated: true
      };
    } catch (error) {
      console.error('Error generating document with AI:', error);
      throw new Error(`Failed to generate ${request.documentType}: ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
  }

  async generateMultipleDocuments(requests: DocumentGenerationRequest[]): Promise<GeneratedDocument[]> {
    const documents: GeneratedDocument[] = [];
    
    // Process documents in parallel for better performance
    const promises = requests.map(request => this.generateComplianceDocument(request));
    const results = await Promise.allSettled(promises);
    
    results.forEach((result, index) => {
      if (result.status === 'fulfilled') {
        documents.push(result.value);
      } else {
        console.error(`Failed to generate ${requests[index].documentType}:`, result.reason);
      }
    });
    
    return documents;
  }

  private buildDocumentPrompt(request: DocumentGenerationRequest): string {
    const orgName = request.organizationName || '[Training Center Name]';
    
    switch (request.documentType) {
      case 'TRAINING_RECORD_TEMPLATE':
        return `Generate a comprehensive FAR Part 142 training record template for ${orgName}. Include all required fields per 14 CFR 142.73:
        - Student identification and certificates
        - Course information and prerequisites
        - Training hours (ground, flight, simulator, FTD)
        - Stage check results and instructor endorsements
        - Knowledge and practical test results
        - Completion certification
        
        Format as a professional form with clear sections and fillable fields. Include regulatory references.`;

      case 'INSTRUCTOR_QUALIFICATION_MATRIX':
        return `Create an instructor qualification tracking matrix for ${orgName} compliant with FAR 142.53-142.59. Include:
        - Instructor identification and certificates
        - Currency tracking (medical, BFR, proficiency checks)
        - Authorization status and limitations
        - Training completion records
        - Alert system for upcoming expirations
        
        Format as a comprehensive tracking system with tables and checklists.`;

      case 'QUALITY_ASSURANCE_MANUAL':
        return `Develop a Quality Assurance Manual for ${orgName} per FAR 142.37. Include:
        - Quality policy and objectives
        - Organization and responsibilities
        - Training program evaluation procedures
        - Instructor performance monitoring
        - Corrective action procedures
        - Audit and review processes
        
        Structure as a complete manual with numbered sections and professional formatting.`;

      case 'EQUIPMENT_MAINTENANCE_LOG':
        return `Create equipment maintenance logs for ${orgName} flight training equipment per FAR 142.39. Include:
        - Equipment identification and specifications
        - Maintenance requirements and schedules
        - Inspection records and discrepancy tracking
        - Airworthiness status and certifications
        - Training device qualifications
        
        Format as comprehensive logging forms with tables and tracking sections.`;

      case 'SMS_MANUAL':
        return `Generate a Safety Management System manual for ${orgName}. Include:
        - Safety policy and objectives
        - Safety accountability and responsibilities
        - Safety risk management procedures
        - Safety assurance processes
        - Safety promotion and training
        
        Structure as a complete SMS manual with detailed procedures and implementation guidance.`;

      case 'CURRICULUM_OUTLINE_TEMPLATE':
        return `Create curriculum outline templates for ${orgName} training courses per FAR 142.13. Include:
        - Course identification and objectives
        - Ground and flight training curricula
        - Testing requirements and standards
        - Instructor qualifications
        - Completion criteria
        
        Format as professional course development templates.`;

      case 'STUDENT_RECORDS_TEMPLATE':
        return `Develop student record templates for ${orgName} per FAR 142.73. Include:
        - Student identification and prerequisites
        - Training progress tracking
        - Assessment results and endorsements
        - Completion documentation
        - Record retention requirements
        
        Format as comprehensive student file templates.`;

      case 'INSTRUCTOR_TRAINING_RECORD':
        return `Create instructor training record templates for ${orgName}. Include:
        - Instructor qualifications and certifications
        - Initial and recurrent training records
        - Proficiency check documentation
        - Performance evaluations
        - Authorization tracking
        
        Format as complete instructor personnel files.`;

      default:
        return `Generate a professional compliance document of type ${request.documentType} for ${orgName}. Ensure FAR Part 142 compliance with proper formatting, required fields, and regulatory references.`;
    }
  }

  private generateFilename(documentType: string): string {
    const timestamp = new Date().toISOString().split('T')[0];
    const typeMap: { [key: string]: string } = {
      'TRAINING_RECORD_TEMPLATE': 'Training_Record_Template',
      'INSTRUCTOR_QUALIFICATION_MATRIX': 'Instructor_Qualification_Matrix',
      'QUALITY_ASSURANCE_MANUAL': 'Quality_Assurance_Manual',
      'EQUIPMENT_MAINTENANCE_LOG': 'Equipment_Maintenance_Log',
      'SMS_MANUAL': 'Safety_Management_System_Manual',
      'CURRICULUM_OUTLINE_TEMPLATE': 'Curriculum_Outline_Template',
      'STUDENT_RECORDS_TEMPLATE': 'Student_Records_Template',
      'INSTRUCTOR_TRAINING_RECORD': 'Instructor_Training_Record'
    };
    
    const baseName = typeMap[documentType] || documentType;
    return `${baseName}_AI_Generated_${timestamp}.txt`;
  }

  private getRegulatoryBasis(documentType: string): string {
    const basisMap: { [key: string]: string } = {
      'TRAINING_RECORD_TEMPLATE': 'FAR 142.73',
      'INSTRUCTOR_QUALIFICATION_MATRIX': 'FAR 142.53-142.59',
      'QUALITY_ASSURANCE_MANUAL': 'FAR 142.37',
      'EQUIPMENT_MAINTENANCE_LOG': 'FAR 142.39',
      'SMS_MANUAL': 'SMS Requirements',
      'CURRICULUM_OUTLINE_TEMPLATE': 'FAR 142.13, 142.37',
      'STUDENT_RECORDS_TEMPLATE': 'FAR 142.73',
      'INSTRUCTOR_TRAINING_RECORD': 'FAR 142.53-142.59'
    };
    
    return basisMap[documentType] || 'FAR Part 142';
  }

  async analyzeDocumentGaps(existingDocuments: any[], complianceResults: any[]): Promise<{
    missingDocuments: string[];
    canAutoGenerate: string[];
    requiresExternalUpload: string[];
    generationPriority: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
  }> {
    try {
      const prompt = `Analyze the following training center documentation for FAR Part 142 compliance gaps:

Existing Documents: ${JSON.stringify(existingDocuments.map(d => ({ type: d.documentType, filename: d.filename })))}

Compliance Issues: ${JSON.stringify(complianceResults.filter(r => r.complianceStatus !== 'COMPLIANT').map(r => ({ item: r.checklistItem, status: r.complianceStatus, risk: r.riskLevel })))}

Based on this analysis, identify:
1. Missing internal documents that can be auto-generated
2. External documents requiring manual upload
3. Overall priority level for document generation

Respond in JSON format with: { "missingDocuments": [], "canAutoGenerate": [], "requiresExternalUpload": [], "generationPriority": "HIGH" }`;

      const response = await openai.chat.completions.create({
        model: "gpt-4o",
        messages: [
          {
            role: "system",
            content: "You are a FAR Part 142 compliance expert. Analyze documentation gaps and provide specific recommendations for training centers."
          },
          {
            role: "user",
            content: prompt
          }
        ],
        response_format: { type: "json_object" },
        temperature: 0.2
      });

      const analysis = JSON.parse(response.choices[0].message.content || '{}');
      
      return {
        missingDocuments: analysis.missingDocuments || [],
        canAutoGenerate: analysis.canAutoGenerate || [
          'TRAINING_RECORD_TEMPLATE', 'INSTRUCTOR_QUALIFICATION_MATRIX', 
          'QUALITY_ASSURANCE_MANUAL', 'EQUIPMENT_MAINTENANCE_LOG',
          'SMS_MANUAL', 'CURRICULUM_OUTLINE_TEMPLATE', 
          'STUDENT_RECORDS_TEMPLATE', 'INSTRUCTOR_TRAINING_RECORD'
        ],
        requiresExternalUpload: analysis.requiresExternalUpload || [
          'Current FAA Training Center Certificate',
          'Chief Flight Instructor Certificate and Medical',
          'Training Specifications (FAA Approved)',
          'Aircraft Registration and Airworthiness Certificates',
          'Simulator Qualification Certificates'
        ],
        generationPriority: analysis.generationPriority || 'HIGH'
      };
    } catch (error) {
      console.error('Error analyzing document gaps:', error);
      // Return default analysis if AI fails
      return {
        missingDocuments: ['TRAINING_RECORD_TEMPLATE', 'INSTRUCTOR_QUALIFICATION_MATRIX', 'QUALITY_ASSURANCE_MANUAL'],
        canAutoGenerate: ['TRAINING_RECORD_TEMPLATE', 'INSTRUCTOR_QUALIFICATION_MATRIX', 'QUALITY_ASSURANCE_MANUAL'],
        requiresExternalUpload: ['Current FAA Training Center Certificate', 'Chief Flight Instructor Certificate'],
        generationPriority: 'HIGH'
      };
    }
  }
}

export const aiDocumentGenerator = new AIDocumentGenerator();