import OpenAI from "openai";
import * as fs from "fs";
import * as path from "path";
import { randomUUID } from "crypto";
import { storage } from "../storage";

// Load environment variables
const envPath = path.join(process.cwd(), '.env');
if (fs.existsSync(envPath)) {
  const envContent = fs.readFileSync(envPath, 'utf8');
  const envLines = envContent.split('\n').filter(line => line.trim() && !line.startsWith('#'));
  for (const line of envLines) {
    const [key, ...valueParts] = line.split('=');
    if (key && valueParts.length > 0) {
      process.env[key.trim()] = valueParts.join('=').trim();
    }
  }
}

const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY || 'not-configured',
});

export interface GeneratedDocument {
  filename: string;
  content: string;
  documentType: string;
  metadata: any;
  autoGenerated: boolean;
}

export interface DocumentGapAnalysis {
  missingDocuments: string[];
  canAutoGenerate: string[];
  requiresExternalUpload: string[];
  generationPriority: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
}

export class DocumentGenerator {
  
  async analyzeDocumentGaps(
    checklistItems: any[],
    existingDocuments: any[],
    organizationData: any
  ): Promise<DocumentGapAnalysis> {
    // Identify what documents are missing for compliance
    const requiredDocuments = this.getRequiredDocuments(checklistItems);
    const existingDocumentTypes = existingDocuments.map(doc => doc.documentType);
    
    const missingDocuments = requiredDocuments.filter(
      docType => !existingDocumentTypes.includes(docType)
    );
    
    // Determine which can be auto-generated vs need external upload
    const canAutoGenerate: string[] = [];
    const requiresExternalUpload: string[] = [];
    
    for (const docType of missingDocuments) {
      if (this.canGenerateDocumentType(docType)) {
        canAutoGenerate.push(docType);
      } else {
        requiresExternalUpload.push(docType);
      }
    }
    
    const generationPriority = this.calculateGenerationPriority(missingDocuments);
    
    return {
      missingDocuments,
      canAutoGenerate,
      requiresExternalUpload,
      generationPriority
    };
  }
  
  async autoGenerateComplianceDocuments(
    userId: string,
    organizationId: string,
    documentTypes: string[],
    existingData: any
  ): Promise<GeneratedDocument[]> {
    const generatedDocuments: GeneratedDocument[] = [];
    
    // Get organization data for context - TODO: implement getOrganization in storage
    const organization = { 
      name: existingData.organizationName || 'Training Center', 
      type: existingData.organizationType || 'Part 142',
      regulatoryId: existingData.regulatoryId || 'TBD'
    };
    
    for (const docType of documentTypes) {
      if (this.canGenerateDocumentType(docType)) {
        const generatedDoc = await this.generateDocumentByType(
          docType,
          organization,
          existingData
        );
        
        if (generatedDoc) {
          generatedDocuments.push(generatedDoc);
          
          // Save generated document to database
          await this.saveGeneratedDocument(
            userId,
            organizationId,
            generatedDoc
          );
        }
      }
    }
    
    return generatedDocuments;
  }
  
  private canGenerateDocumentType(documentType: string): boolean {
    const generatableTypes = [
      'TRAINING_RECORD_TEMPLATE',
      'INSTRUCTOR_QUALIFICATION_MATRIX',
      'CURRICULUM_OUTLINE',
      'SAFETY_POLICY_TEMPLATE',
      'RECORD_RETENTION_POLICY',
      'STUDENT_PROGRESS_TEMPLATE',
      'COURSE_COMPLETION_CERTIFICATE',
      'PROFICIENCY_CHECK_FORM',
      'TRAINING_SYLLABUS_OUTLINE',
      'LESSON_PLAN_TEMPLATE',
      'EQUIPMENT_CHECKLIST',
      'EMERGENCY_PROCEDURES',
      'QUALITY_ASSURANCE_CHECKLIST'
    ];
    
    return generatableTypes.includes(documentType);
  }
  
  private async generateDocumentByType(
    documentType: string,
    organization: any,
    existingData: any
  ): Promise<GeneratedDocument | null> {
    
    switch (documentType) {
      case 'TRAINING_RECORD_TEMPLATE':
        return this.generateTrainingRecordTemplate(organization, existingData);
      
      case 'INSTRUCTOR_QUALIFICATION_MATRIX':
        return this.generateInstructorMatrix(organization, existingData);
      
      case 'CURRICULUM_OUTLINE':
        return this.generateCurriculumOutline(organization, existingData);
      
      case 'SAFETY_POLICY_TEMPLATE':
        return this.generateSafetyPolicy(organization, existingData);
      
      case 'RECORD_RETENTION_POLICY':
        return this.generateRetentionPolicy(organization, existingData);
      
      case 'COURSE_COMPLETION_CERTIFICATE':
        return this.generateCompletionCertificate(organization, existingData);
      
      case 'PROFICIENCY_CHECK_FORM':
        return this.generateProficiencyCheckForm(organization, existingData);
      
      case 'TRAINING_SYLLABUS_OUTLINE':
        return this.generateSyllabusOutline(organization, existingData);
      
      default:
        return null;
    }
  }
  
  private async generateTrainingRecordTemplate(
    organization: any,
    existingData: any
  ): Promise<GeneratedDocument> {
    
    const prompt = `Generate a comprehensive FAR Part 142 compliant training record template for ${organization.name}.

    The template must include all required fields per FAR 142.73:
    1. Name of the trainee
    2. Copy of trainee's pilot certificate and medical certificate
    3. Course name and make/model of flight training equipment
    4. Prerequisite experience and course time completed
    5. Detailed curriculum showing approved course outline
    6. Record of flight, flight simulator, flight training device, and ground time
    7. Ground school attendance records
    8. Results of stage checks and end-of-course tests
    9. Instructor endorsements showing the instructor's signature and certificate number
    10. Line check records if applicable

    Organization Type: ${organization.type}
    Regulatory ID: ${organization.regulatoryId}

    Format as a professional training record template with clear sections and form fields.
    Include compliance notes referencing specific FAR regulations.`;

    try {
      const response = await openai.chat.completions.create({
        model: "gpt-4o", // the newest OpenAI model is "gpt-4o" which was released May 13, 2024. do not change this unless explicitly requested by the user
        messages: [
          {
            role: "system",
            content: "You are an expert aviation training compliance specialist. Generate professional, FAR-compliant training documentation."
          },
          {
            role: "user",
            content: prompt
          }
        ],
        temperature: 0.3,
      });

      const content = response.choices[0].message.content || "";

      return {
        filename: `Training_Record_Template_${organization.name.replace(/\s+/g, '_')}.txt`,
        content,
        documentType: 'TRAINING_RECORD_TEMPLATE',
        metadata: {
          organization: organization.name,
          regulatoryBasis: 'FAR 142.73',
          generatedAt: new Date().toISOString()
        },
        autoGenerated: true
      };
    } catch (error) {
      console.error('Error generating training record template:', error);
      throw error;
    }
  }
  
  private async generateInstructorMatrix(
    organization: any,
    existingData: any
  ): Promise<GeneratedDocument> {
    
    const prompt = `Generate a comprehensive instructor qualification matrix for ${organization.name}.

    The matrix must track all FAR Part 142 instructor requirements:
    - Instructor certificates and ratings
    - Currency requirements (flight review, medical certificate, etc.)
    - Proficiency check requirements and due dates
    - Training courses completed
    - Authorization to conduct specific training
    - Qualification expiration tracking

    Organization Type: ${organization.type}
    Regulatory ID: ${organization.regulatoryId}

    Create a tabular format that can track multiple instructors with all required qualifications.
    Include compliance deadlines and renewal requirements.`;

    try {
      const response = await openai.chat.completions.create({
        model: "gpt-4o", // the newest OpenAI model is "gpt-4o" which was released May 13, 2024. do not change this unless explicitly requested by the user
        messages: [
          {
            role: "system",
            content: "You are an expert aviation training compliance specialist. Generate professional instructor qualification tracking matrices."
          },
          {
            role: "user",
            content: prompt
          }
        ],
        temperature: 0.3,
      });

      const content = response.choices[0].message.content || "";

      return {
        filename: `Instructor_Qualification_Matrix_${organization.name.replace(/\s+/g, '_')}.txt`,
        content,
        documentType: 'INSTRUCTOR_QUALIFICATION_MATRIX',
        metadata: {
          organization: organization.name,
          regulatoryBasis: 'FAR 142.51-142.59',
          generatedAt: new Date().toISOString()
        },
        autoGenerated: true
      };
    } catch (error) {
      console.error('Error generating instructor matrix:', error);
      throw error;
    }
  }
  
  private async generateCurriculumOutline(
    organization: any,
    existingData: any
  ): Promise<GeneratedDocument> {
    
    const courseTypes = existingData.courseTypes || ['Initial', 'Recurrent', 'Upgrade'];
    
    const prompt = `Generate a detailed curriculum outline template for ${organization.name}.

    The curriculum must be structured per FAR Part 142 requirements with:
    - Clear learning objectives for each module
    - Ground school curriculum with hours allocated
    - Flight training curriculum with hours allocated
    - Prerequisites for each course level
    - Performance standards and completion criteria
    - Required equipment and facilities

    Course Types to Include: ${courseTypes.join(', ')}
    Organization Type: ${organization.type}

    Structure as a comprehensive curriculum outline that meets FAA approval requirements.
    Include detailed learning objectives and measurable performance standards.`;

    try {
      const response = await openai.chat.completions.create({
        model: "gpt-4o", // the newest OpenAI model is "gpt-4o" which was released May 13, 2024. do not change this unless explicitly requested by the user
        messages: [
          {
            role: "system",
            content: "You are an expert aviation curriculum developer. Generate FAA-compliant training curriculum outlines."
          },
          {
            role: "user",
            content: prompt
          }
        ],
        temperature: 0.3,
      });

      const content = response.choices[0].message.content || "";

      return {
        filename: `Curriculum_Outline_${organization.name.replace(/\s+/g, '_')}.txt`,
        content,
        documentType: 'CURRICULUM_OUTLINE',
        metadata: {
          organization: organization.name,
          courseTypes,
          regulatoryBasis: 'FAR 142.37-142.39',
          generatedAt: new Date().toISOString()
        },
        autoGenerated: true
      };
    } catch (error) {
      console.error('Error generating curriculum outline:', error);
      throw error;
    }
  }
  
  private async generateSafetyPolicy(
    organization: any,
    existingData: any
  ): Promise<GeneratedDocument> {
    
    const prompt = `Generate a comprehensive Safety Management System (SMS) policy for ${organization.name}.

    The policy must address FAR Part 142 safety requirements including:
    - Safety policy and objectives
    - Safety responsibilities and accountabilities
    - Safety risk management procedures
    - Safety assurance processes
    - Safety promotion and training
    - Emergency response procedures
    - Incident and accident reporting

    Organization Type: ${organization.type}
    Regulatory ID: ${organization.regulatoryId}

    Create a professional safety policy document that demonstrates compliance with SMS requirements.`;

    try {
      const response = await openai.chat.completions.create({
        model: "gpt-4o", // the newest OpenAI model is "gpt-4o" which was released May 13, 2024. do not change this unless explicitly requested by the user
        messages: [
          {
            role: "system",
            content: "You are an expert aviation safety management specialist. Generate comprehensive SMS policy documents."
          },
          {
            role: "user",
            content: prompt
          }
        ],
        temperature: 0.3,
      });

      const content = response.choices[0].message.content || "";

      return {
        filename: `Safety_Management_Policy_${organization.name.replace(/\s+/g, '_')}.txt`,
        content,
        documentType: 'SAFETY_POLICY_TEMPLATE',
        metadata: {
          organization: organization.name,
          regulatoryBasis: 'FAR 142.3, SMS Requirements',
          generatedAt: new Date().toISOString()
        },
        autoGenerated: true
      };
    } catch (error) {
      console.error('Error generating safety policy:', error);
      throw error;
    }
  }
  
  private async generateRetentionPolicy(
    organization: any,
    existingData: any
  ): Promise<GeneratedDocument> {
    
    const prompt = `Generate a comprehensive record retention policy for ${organization.name}.

    The policy must specify retention periods per FAR Part 142:
    - Training records: 5 years after completion
    - Instructor qualification records: Current plus 5 years
    - Course approval documentation: Current plus historical versions
    - Student progress records: 5 years after completion
    - Equipment maintenance records: As required by manufacturer
    - Safety management records: 5 years minimum

    Organization Type: ${organization.type}
    
    Create a detailed policy covering all required record types, retention periods, and storage requirements.
    Include procedures for record disposal and archive management.`;

    try {
      const response = await openai.chat.completions.create({
        model: "gpt-4o", // the newest OpenAI model is "gpt-4o" which was released May 13, 2024. do not change this unless explicitly requested by the user
        messages: [
          {
            role: "system",
            content: "You are an expert aviation records management specialist. Generate comprehensive record retention policies."
          },
          {
            role: "user",
            content: prompt
          }
        ],
        temperature: 0.3,
      });

      const content = response.choices[0].message.content || "";

      return {
        filename: `Record_Retention_Policy_${organization.name.replace(/\s+/g, '_')}.txt`,
        content,
        documentType: 'RECORD_RETENTION_POLICY',
        metadata: {
          organization: organization.name,
          regulatoryBasis: 'FAR 142.73, Record Retention Requirements',
          generatedAt: new Date().toISOString()
        },
        autoGenerated: true
      };
    } catch (error) {
      console.error('Error generating retention policy:', error);
      throw error;
    }
  }
  
  private async generateCompletionCertificate(
    organization: any,
    existingData: any
  ): Promise<GeneratedDocument> {
    
    const prompt = `Generate a professional course completion certificate template for ${organization.name}.

    The certificate template should include:
    - Student name and certificate number fields
    - Course name and type completed
    - Completion date and location
    - Training hours completed (ground and flight)
    - Instructor signature and certificate number
    - Organization name and approval number
    - FAR compliance statement

    Organization Type: ${organization.type}
    Regulatory ID: ${organization.regulatoryId}

    Create a formal certificate template suitable for professional presentation.
    Include all required regulatory references and compliance statements.`;

    try {
      const response = await openai.chat.completions.create({
        model: "gpt-4o", // the newest OpenAI model is "gpt-4o" which was released May 13, 2024. do not change this unless explicitly requested by the user
        messages: [
          {
            role: "system",
            content: "You are an expert aviation training certificate designer. Generate professional completion certificates."
          },
          {
            role: "user",
            content: prompt
          }
        ],
        temperature: 0.3,
      });

      const content = response.choices[0].message.content || "";

      return {
        filename: `Course_Completion_Certificate_${organization.name.replace(/\s+/g, '_')}.txt`,
        content,
        documentType: 'COURSE_COMPLETION_CERTIFICATE',
        metadata: {
          organization: organization.name,
          regulatoryBasis: 'FAR 142.73, Training Record Requirements',
          generatedAt: new Date().toISOString()
        },
        autoGenerated: true
      };
    } catch (error) {
      console.error('Error generating completion certificate:', error);
      throw error;
    }
  }
  
  private async generateProficiencyCheckForm(
    organization: any,
    existingData: any
  ): Promise<GeneratedDocument> {
    
    const prompt = `Generate a comprehensive proficiency check form for ${organization.name}.

    The form must include evaluation sections for:
    - Instructor knowledge and experience
    - Teaching techniques and effectiveness
    - Safety practices and procedures
    - Aircraft systems knowledge (if applicable)
    - Emergency procedures competency
    - Regulatory knowledge assessment
    - Overall performance rating

    Organization Type: ${organization.type}
    
    Create a detailed evaluation form with scoring criteria and pass/fail standards.
    Include sections for evaluator comments and recommendations.`;

    try {
      const response = await openai.chat.completions.create({
        model: "gpt-4o", // the newest OpenAI model is "gpt-4o" which was released May 13, 2024. do not change this unless explicitly requested by the user
        messages: [
          {
            role: "system",
            content: "You are an expert aviation instructor evaluator. Generate comprehensive proficiency check forms."
          },
          {
            role: "user",
            content: prompt
          }
        ],
        temperature: 0.3,
      });

      const content = response.choices[0].message.content || "";

      return {
        filename: `Proficiency_Check_Form_${organization.name.replace(/\s+/g, '_')}.txt`,
        content,
        documentType: 'PROFICIENCY_CHECK_FORM',
        metadata: {
          organization: organization.name,
          regulatoryBasis: 'FAR 142.53, Instructor Proficiency Requirements',
          generatedAt: new Date().toISOString()
        },
        autoGenerated: true
      };
    } catch (error) {
      console.error('Error generating proficiency check form:', error);
      throw error;
    }
  }
  
  private async generateSyllabusOutline(
    organization: any,
    existingData: any
  ): Promise<GeneratedDocument> {
    
    const prompt = `Generate a detailed training syllabus outline for ${organization.name}.

    The syllabus should include:
    - Course objectives and learning outcomes
    - Lesson-by-lesson breakdown with hours
    - Prerequisites and completion standards
    - Required materials and equipment
    - Assessment methods and criteria
    - Progress tracking milestones

    Organization Type: ${organization.type}
    
    Structure as a comprehensive syllabus that meets FAA training program requirements.
    Include both ground school and practical training components.`;

    try {
      const response = await openai.chat.completions.create({
        model: "gpt-4o", // the newest OpenAI model is "gpt-4o" which was released May 13, 2024. do not change this unless explicitly requested by the user
        messages: [
          {
            role: "system",
            content: "You are an expert aviation curriculum developer. Generate detailed training syllabi."
          },
          {
            role: "user",
            content: prompt
          }
        ],
        temperature: 0.3,
      });

      const content = response.choices[0].message.content || "";

      return {
        filename: `Training_Syllabus_${organization.name.replace(/\s+/g, '_')}.txt`,
        content,
        documentType: 'TRAINING_SYLLABUS_OUTLINE',
        metadata: {
          organization: organization.name,
          regulatoryBasis: 'FAR 142.37, Approved Training Programs',
          generatedAt: new Date().toISOString()
        },
        autoGenerated: true
      };
    } catch (error) {
      console.error('Error generating syllabus outline:', error);
      throw error;
    }
  }
  
  private getRequiredDocuments(checklistItems: any[]): string[] {
    const documentMap: { [category: string]: string[] } = {
      'Personnel': [
        'INSTRUCTOR_QUALIFICATION_MATRIX',
        'PROFICIENCY_CHECK_FORM',
        'TRAINING_RECORD_TEMPLATE'
      ],
      'Curriculum and Courseware': [
        'CURRICULUM_OUTLINE',
        'TRAINING_SYLLABUS_OUTLINE',
        'LESSON_PLAN_TEMPLATE'
      ],
      'Training Records': [
        'TRAINING_RECORD_TEMPLATE',
        'STUDENT_PROGRESS_TEMPLATE',
        'COURSE_COMPLETION_CERTIFICATE'
      ],
      'Quality Assurance': [
        'QUALITY_ASSURANCE_CHECKLIST',
        'RECORD_RETENTION_POLICY'
      ],
      'Safety Management': [
        'SAFETY_POLICY_TEMPLATE',
        'EMERGENCY_PROCEDURES'
      ]
    };
    
    const requiredDocs: string[] = [];
    
    checklistItems.forEach(item => {
      const docsForCategory = documentMap[item.category] || [];
      docsForCategory.forEach(doc => {
        if (!requiredDocs.includes(doc)) {
          requiredDocs.push(doc);
        }
      });
    });
    
    return requiredDocs;
  }
  
  private calculateGenerationPriority(missingDocuments: string[]): 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL' {
    const criticalDocs = ['TRAINING_RECORD_TEMPLATE', 'INSTRUCTOR_QUALIFICATION_MATRIX', 'SAFETY_POLICY_TEMPLATE'];
    const highPriorityDocs = ['CURRICULUM_OUTLINE', 'PROFICIENCY_CHECK_FORM', 'RECORD_RETENTION_POLICY'];
    
    const hasCritical = missingDocuments.some(doc => criticalDocs.includes(doc));
    const hasHighPriority = missingDocuments.some(doc => highPriorityDocs.includes(doc));
    
    if (hasCritical) return 'CRITICAL';
    if (hasHighPriority) return 'HIGH';
    if (missingDocuments.length > 3) return 'MEDIUM';
    return 'LOW';
  }
  
  private async saveGeneratedDocument(
    userId: string,
    organizationId: string,
    generatedDoc: GeneratedDocument
  ): Promise<void> {
    // Save the generated document content to file system
    const uploadsDir = path.join(process.cwd(), 'uploads');
    if (!fs.existsSync(uploadsDir)) {
      fs.mkdirSync(uploadsDir, { recursive: true });
    }
    
    // Generated filenames are deterministic per document type, so prefix the
    // persisted file with a UUID to keep every generation's content distinct —
    // otherwise a re-run would overwrite the file older DB rows point at.
    const storedFilename = `${randomUUID()}-${generatedDoc.filename}`;
    const filePath = path.join(uploadsDir, storedFilename);
    fs.writeFileSync(filePath, generatedDoc.content, 'utf8');

    // Durably persist a record of the generated document. Let errors propagate
    // so persistence failures surface to the caller rather than silently
    // leaving the on-disk file unindexed.
    await storage.createGeneratedDocument({
      filename: generatedDoc.filename,
      documentType: generatedDoc.documentType,
      fileSize: Buffer.byteLength(generatedDoc.content, 'utf8'),
      filePath,
      metadata: generatedDoc.metadata,
      generatedBy: userId,
      organizationId: organizationId ?? null,
    });
  }
}

export const documentGenerator = new DocumentGenerator();